/**
 * The scenarios that exist, bound to the checks they cover.
 *
 * GENERATED by `gen-scenarios.ts`. Do not edit — edit the anchor table there.
 *
 * `coveredTextWas` comes from the specification rather than being typed, so a
 * scenario cannot be born already drifted. Regenerate after deliberately
 * re-reading a changed check, never to silence a drift report.
 *
 * A scenario here is a *claim* that something is observed, and the claim is
 * checked twice: `write-log.ts` counts it only when a test bearing its id passed,
 * and `coverage.test.ts` fails when an entry has no test behind it. Declaring an
 * entry is not a way to raise the coverage number.
 */
import type { Scenario } from './checks.js';

export const scenarios: readonly Scenario[] = [
  {
    id: "offer-needs-published-listing",
    covers: "S3-04",
    kind: "rejects",
    coveredTextWas:
      "The candidate MUST NOT accept an offer that references no published listing activity " +
      "(Section 2.9).",
  },
  {
    id: "submission-correlates-to-offer",
    covers: "S3-05",
    kind: "resolves",
    coveredTextWas:
      "Every `OfferSubmission` the candidate accepts MUST correlate to an `Offer` it holds, " +
      "by `OfferId`. A candidate that accepts a submission correlating to no offer fails " +
      "(Section 2.5).",
  },
  {
    id: "property-group-resolves",
    covers: "S3-06",
    kind: "resolves",
    coveredTextWas:
      "Every `OfferSubmission` the candidate accepts MUST carry an `OfferPropertyGroupKey` " +
      "that resolves, whether the group travels inline or by key (Section 2.6).",
  },
  {
    id: "property-group-inline-or-by-key",
    covers: "S3-06",
    kind: "accepts",
    coveredTextWas:
      "Every `OfferSubmission` the candidate accepts MUST carry an `OfferPropertyGroupKey` " +
      "that resolves, whether the group travels inline or by key (Section 2.6).",
  },
  {
    id: "either-payload-form",
    covers: "S3-07",
    kind: "accepts",
    coveredTextWas:
      "The candidate MUST accept a submission both on its own and expanded into its `Offer` " +
      "under `Submissions`, and MUST NOT require the expanded form (Section 2.5).",
  },
  {
    id: "second-offer-both-live",
    covers: "S3-08",
    kind: "accepts",
    coveredTextWas:
      "The candidate MUST accept a second `Offer` from the same buyer on the same listing, " +
      "both where an earlier offer has ended and where both are live. A candidate that " +
      "rejects it as a duplicate, or that merges it into the earlier offer, fails (Section " +
      "2.4).",
  },
  {
    id: "second-offer-after-ended",
    covers: "S3-08",
    kind: "accepts",
    coveredTextWas:
      "The candidate MUST accept a second `Offer` from the same buyer on the same listing, " +
      "both where an earlier offer has ended and where both are live. A candidate that " +
      "rejects it as a duplicate, or that merges it into the earlier offer, fails (Section " +
      "2.4).",
  },
  {
    id: "ended-offer-takes-no-turns",
    covers: "S3-09",
    kind: "rejects",
    coveredTextWas:
      "The candidate MUST NOT append a submission to an offer that has been withdrawn, " +
      "rejected or has expired (Section 2.4).",
  },
  {
    id: "coordinate-needs-system-member",
    covers: "S3-10",
    kind: "present",
    coveredTextWas:
      "An `Offer` the candidate accepts MUST carry `ListingId` or `ListingKey`, and MUST " +
      "carry at least one of `OfferOriginatingSystemName` or `OfferOriginatingSystemId`. An " +
      "`Offer` carrying `OfferUoi` and neither of that pair fails. A candidate that accepts a " +
      "listing identifier with no organization or system member fails (Section 2.4).",
  },
  {
    id: "coordinate-refused-before-store",
    covers: "S3-10",
    kind: "rejects",
    coveredTextWas:
      "An `Offer` the candidate accepts MUST carry `ListingId` or `ListingKey`, and MUST " +
      "carry at least one of `OfferOriginatingSystemName` or `OfferOriginatingSystemId`. An " +
      "`Offer` carrying `OfferUoi` and neither of that pair fails. A candidate that accepts a " +
      "listing identifier with no organization or system member fails (Section 2.4).",
  },
  {
    id: "superseded-submission-frozen",
    covers: "S3-13",
    kind: "immutable",
    coveredTextWas:
      "On a counter, the candidate MUST create a new `OfferSubmission`, and every submission " +
      "that was already superseded MUST remain byte-identical to what it held when the " +
      "counter was created (Section 2.9). A candidate that modifies a superseded submission " +
      "fails.",
  },
  {
    id: "counter-leaves-prior-intact",
    covers: "S3-13",
    kind: "immutable",
    coveredTextWas:
      "On a counter, the candidate MUST create a new `OfferSubmission`, and every submission " +
      "that was already superseded MUST remain byte-identical to what it held when the " +
      "counter was created (Section 2.9). A candidate that modifies a superseded submission " +
      "fails.",
  },
  {
    id: "expansion-is-read-only",
    covers: "S3-14",
    kind: "refuses",
    coveredTextWas:
      "The candidate MUST NOT create, alter or remove a submission through the `Submissions` " +
      "expansion (Section 2.5).",
  },
  {
    id: "no-terms-act-adds-no-submission",
    covers: "S3-15",
    kind: "absent",
    coveredTextWas:
      "The candidate MUST record an act that changes no terms by setting its own status field " +
      "on the current submission, and MUST NOT create a submission for it. A candidate that " +
      "emits a submission for an acknowledgement, acceptance, rejection or withdrawal fails " +
      "(Section 2.7).",
  },
  {
    id: "current-state-is-highest-sequence",
    covers: "S3-16",
    kind: "derives",
    coveredTextWas:
      "The current state the candidate reports for an offer MUST equal the pair of statuses " +
      "on its highest-sequence submission, at every point in the exchange (Section 2.7).",
  },
  {
    id: "only-own-side-status",
    covers: "S3-17",
    kind: "immutable",
    coveredTextWas:
      "The candidate MUST NOT set the counterparty's status field, and MUST NOT reject an " +
      "offer whose two status fields disagree (Section 2.7).",
  },
  {
    id: "disagreeing-statuses-allowed",
    covers: "S3-17",
    kind: "accepts",
    coveredTextWas:
      "The candidate MUST NOT set the counterparty's status field, and MUST NOT reject an " +
      "offer whose two status fields disagree (Section 2.7).",
  },
  {
    id: "sequence-is-max-plus-one",
    covers: "S3-18",
    kind: "sequence",
    coveredTextWas:
      "Every submission the candidate creates MUST carry `OfferSubmissionSequence` set to one " +
      "greater than the highest it has seen for that `OfferId`, or to 1 for the first, and " +
      "MUST keep that value unchanged thereafter (Section 2.9).",
  },
  {
    id: "sequence-is-not-a-count",
    covers: "S3-18",
    kind: "sequence",
    coveredTextWas:
      "Every submission the candidate creates MUST carry `OfferSubmissionSequence` set to one " +
      "greater than the highest it has seen for that `OfferId`, or to 1 for the first, and " +
      "MUST keep that value unchanged thereafter (Section 2.9).",
  },
  {
    id: "tie-breaks-on-organization",
    covers: "S3-19",
    kind: "sequence",
    coveredTextWas:
      "Where two submissions of one offer carry the same sequence, the candidate MUST order " +
      "them by the submitting party's Unique Organization Identifier ascending, and MUST NOT " +
      "order them by arrival time (Section 2.9).",
  },
  {
    id: "prior-turns-retrievable",
    covers: "S3-20",
    kind: "sequence",
    coveredTextWas:
      "Every submission created during the test MUST remain retrievable under its `OfferId` " +
      "after later submissions are created, and MUST be returned in `OfferSubmissionSequence` " +
      "order (Section 2.9).",
  },
  {
    id: "turns-in-sequence-order",
    covers: "S3-20",
    kind: "sequence",
    coveredTextWas:
      "Every submission created during the test MUST remain retrievable under its `OfferId` " +
      "after later submissions are created, and MUST be returned in `OfferSubmissionSequence` " +
      "order (Section 2.9).",
  },
  {
    id: "name-only-coordinate-accepted",
    covers: "S3-30",
    kind: "accepts",
    coveredTextWas:
      "The candidate MUST accept a listing coordinate whose organization member is an " +
      "originating system name or identifier, and MUST NOT reject an offer on the ground that " +
      "no organization identifier was supplied for the listing (Section 2.4).",
  },
  {
    id: "payload-refuses-unauthenticated",
    covers: "S3-31",
    kind: "refuses",
    coveredTextWas:
      "Every payload link the candidate publishes MUST refuse an unauthenticated dereference " +
      "(Section 2.11).",
  },
  {
    id: "identity-from-token-only",
    covers: "S3-35",
    kind: "derives",
    coveredTextWas:
      "The candidate MUST determine a requester's identifier from the presented token and " +
      "MUST NOT infer it from a value carried in the request (Section 2.11).",
  },
  {
    id: "no-delegated-entitlement",
    covers: "S3-36",
    kind: "refuses",
    coveredTextWas:
      "The candidate MUST NOT accept another participant's assertion that a requester is " +
      "entitled to an offer in place of its own determination (Section 2.11).",
  },
  {
    id: "non-party-refused",
    covers: "S3-37",
    kind: "refuses",
    coveredTextWas:
      "The candidate MUST refuse to serve offer content to a requester outside the parties to " +
      "that offer (Section 2.11).",
  },
  {
    id: "withheld-buyer-fields-not-an-error",
    covers: "S3-39",
    kind: "present",
    coveredTextWas:
      "The candidate MUST NOT treat the absence of buyer or co-buyer fields as an error " +
      "(Section 2.11).",
  },
  {
    id: "refusal-does-not-disclose-existence",
    covers: "S3-38",
    kind: "refuses",
    coveredTextWas:
      "The candidate MUST answer an unauthenticated request `401`, and MUST give a requester " +
      "who is not entitled to an offer the same status and the same body whether or not that " +
      "offer exists (Section 2.11).",
  },
];
