/**
 * Write the certification log.
 *
 * Generated, never edited. Its value is that it cannot flatter: the checks come
 * from the specification, and coverage comes from **what the suite observed** —
 * not from the scenario registry's own claims. A registry entry with no passing
 * test behind it is reported as declared-but-unverified.
 *
 * That distinction was added after the registry was found to be self-certifying:
 * declaring eight entries would have moved the log from 6 verified to 14 with no
 * assertion written. The log now depends on results, so it cannot be raised by
 * declaration.
 *
 * Run `npm run log`, which runs the suite to a report first.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { coverage, extractChecks, type SpecCheck } from './checks.js';
import { scenarios } from './scenarios.js';
import { isVerified, readSuiteResults, stalenessOf } from './verified.js';
import { certificationLogPath, specPath, testResultsPath } from './paths.js';


const spec = await readFile(specPath, 'utf-8');
const checks = extractChecks(spec);
const declared = coverage(checks, scenarios);
const results = await readSuiteResults(testResultsPath, scenarios.map((s) => s.id));

// Sources the results must be newer than: the specification, the implementation
// and the tests. Reporting stale coverage as current is the quiet failure here.
// Relative to `dist/`, where this runs. The suite runs against `src/` and
// `tests/`, so those are the sources to compare against — never `dist/`, which
// the build rewrites after the tests and would flag every clean run as stale.
const srcDir = new URL('../src/', import.meta.url);
const testDir = new URL('../tests/', import.meta.url);
const sources = [
  specPath,
  ...(await readdir(srcDir)).map((f) => new URL(f, srcDir).pathname),
  ...(await readdir(testDir)).map((f) => new URL(f, testDir).pathname),
];
const staleness = await stalenessOf(testResultsPath, sources);

/** Per check: the scenarios claimed, and of those, the ones the suite verified. */
const claimed = new Map<string, string[]>();
for (const s of scenarios) claimed.set(s.covers, [...(claimed.get(s.covers) ?? []), s.id]);

const verifiedFor = (id: string): string[] =>
  (claimed.get(id) ?? []).filter((s) => isVerified(results, s));
const unexecuted = (id: string): string[] =>
  (claimed.get(id) ?? []).filter((s) => !results.executed.has(s));

const verifiedChecks = checks.filter((c) => verifiedFor(c.id).length > 0);
const orphaned = scenarios.filter((s) => !results.executed.has(s.id));

const kindOf = (id: string): string =>
  [...new Set(scenarios.filter((s) => s.covers === id).map((s) => s.kind))].join(', ');
const section = (c: SpecCheck): string => c.cites[0] ?? '—';

const rows = checks
  .map((c) => {
    const ok = verifiedFor(c.id);
    const missing = unexecuted(c.id);
    const drifted = declared.drifted.some((d) => d.check === c.id);
    const status = drifted
      ? '**DRIFTED**'
      : ok.length > 0
        ? 'verified'
        : missing.length > 0
          ? '**claimed, not run**'
          : 'not verified';
    const by = ok.length > 0 ? `\`${ok.join('`, `')}\`` : '';
    return `| ${c.id} | ${section(c)} | ${status} | ${by} | ${kindOf(c.id)} | ${c.text.replace(/\|/g, '\\|')} |`;
  })
  .join('\n');

const bySection = new Map<string, { total: number; done: number }>();
for (const c of checks) {
  const s = section(c);
  const e = bySection.get(s) ?? { total: 0, done: 0 };
  bySection.set(s, { total: e.total + 1, done: e.done + (verifiedFor(c.id).length > 0 ? 1 : 0) });
}

const md = `# Certification Log

Generated by \`src/write-log.ts\`. **Do not edit.** Regenerate with
\`npm run log\` after any change to the specification, the scenarios or the suite.

The checks are read from Section 3 of
[\`offer-management.md\`](https://github.com/RESOStandards/transport/blob/main/proposals/offer-management.md).
Coverage is read from the test suite's own results – ${results.totalTests} tests, run
${results.ranAt.toISOString().slice(0, 16).replace('T', ' ')}Z, ${results.allPassed ? 'all passing' : '**with failures**'}.
Neither is transcribed, so this log cannot quietly disagree with either.
${staleness.stale ? `\n> **These results are stale.** ${staleness.newer.length} file(s) changed after the suite ran, so the coverage below may not describe the current code. Regenerate with \`npm run log\`.\n` : ''}${results.allPassed ? '' : `\n> **The suite is red.** Coverage below counts only passing scenarios; a failing one is not coverage.\n`}

**${verifiedChecks.length} of ${checks.length} verified.** ${checks.length - verifiedChecks.length} not yet, ${declared.drifted.length} drifted${orphaned.length > 0 ? `, ${orphaned.length} claimed but not run` : ''}.

A check is *verified* only when a scenario bound to it ran in the suite and passed.
A scenario declared in the registry with no test behind it shows as **claimed, not
run** – declaring one does not raise the number. A check is *drifted* when the
specification reworded it after its scenario was written, which means the scenario
may no longer test what it claims; drift keeps its coverage so the ambiguity stays
visible instead of disappearing.

## By Section

| Section | Verified | Total |
| :--- | ---: | ---: |
${[...bySection]
  .sort((a, b) => b[1].total - a[1].total || a[0].localeCompare(b[0]))
  .map(([s, e]) => `| ${s} | ${e.done} | ${e.total} |`)
  .join('\n')}

## Every Check

| Id | Section | Status | Scenarios | Kind | Check |
| :--- | :--- | :--- | :--- | :--- | :--- |
${rows}

## What "Not Verified" Means Here

It means no scenario observes the check, not that a candidate would fail it. The
distinction matters because a certification tool that tests a subset without
saying so reads as a passing grade – which is the failure this log exists to
prevent.
`;

await writeFile(certificationLogPath, md, 'utf-8');
console.log(`  wrote ${certificationLogPath}`);
console.log(
  `  ${verifiedChecks.length}/${checks.length} verified · ${declared.drifted.length} drifted · ${orphaned.length} claimed-not-run · suite ${results.allPassed ? 'green' : 'RED'}${staleness.stale ? ' · results STALE' : ''}`
);

// The log is written either way — a stale green log is worse than a red one —
// but a red suite must not exit 0, or the operator never learns.
if (!results.allPassed) process.exitCode = 1;
